package edu.westminster.ticketingsystem.ticketing_system.model;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * The Transaction class represents a record of a transaction in the ticketing system.
 *
 * Transactions are stored in a database and include details such as the type of transaction,
 * the user involved, ticket count, timestamp, and additional details.
 */
@Entity
@Data
public class Transaction {

    /**
     * The unique identifier for the transaction.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The type of transaction (e.g., "ADD", "RETRIEVE", "CLEAR").
     */
    private String type;

    /**
     * The ID of the user associated with the transaction.
     */
    private String userId;

    /**
     * The type of user associated with the transaction (e.g., "VENDOR", "VIP", "NORMAL").
     */
    private String userType;

    /**
     * The number of tickets involved in the transaction.
     */
    private int ticketCount;

    /**
     * The timestamp when the transaction occurred.
     */
    private LocalDateTime timestamp;

    /**
     * Additional details about the transaction.
     */
    private String details;
}
